name: newsapi2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  loading_indicator: ^3.1.0
  path_provider: ^2.0.11




dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  webview_flutter: ^3.0.4

flutter:

  uses-material-design: true